mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('mystore/', include('mystore.urls')),
    path('admin/', admin.site.urls),


]

mysite/mystore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'mystore'
urlpatterns = [
    path('', views.IndexView, name='index'),
    path('<int:order_id>/', views.detail, name='detail'),
    path('inventory/', views.InventoryListView.as_view(), name='inventory'),
    path('add_order/', views.add_order, name='add_order'),
    path('add_item/', views.add_item, name='add_item'),
    path('<int:order_id>/<slug:institution>/<slug:size>/<int:item_rmv>/', views.detail, name='item_removed'),
    path('<int:order_id>/<slug:institution>/<slug:size>/<int:item_dispatch>/<int:item_pending>', views.detail, name='item_dispatch'),
    path('<int:order_id>/<slug:institution>/<slug:size>/<int:item_missing>/<int:item_pending>/add', views.detail, name='items_pending'),
    path('<int:order_id>/<slug:institution>/', views.detail, name='institution'),
    path('<int:order_id>/<slug:institution>/<slug:size>/', views.detail, name='size'),
    path('confirmation/<int:order_id>/', views.confirmation, name='confirmation'),
    path('receipt/<int:order_id>/', views.receipt, name='receipt'),
    path('order_update/<int:order_id>/', views.order_update, name='order_update'),
    path('order_update/<int:order_id>/<int:item_missing>/<int:item_pending>/return', views.order_update, name='order_return'),
    path('order_update/<int:order_id>/<int:item_dispatch>/<int:item_pending>/remove', views.order_update, name='order_dispatch'),
    path('confirmation/<int:order_id>/share/', views.order_share, name='order_share'),
    path('order_search/', views.order_search, name='order_search'),
    path('item_search/', views.ItemSearchListView.as_view(), name='item_search'),
    path('client_search/', views.client_search, name='client_search'),
    path('client_detail/<int:client>', views.client_detail, name='client_detail'),
    path('add_client/', views.add_client, name='add_client'),
    path('order_receipt/<int:order_id>/pdf', views.order_pdf, name='order_receipt'),
    path('payments/', views.order_payments, name='order_payments'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/mystore/models.py
from datetime import datetime, timedelta

from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify


class Client(models.Model):
    name = models.CharField(max_length=60, verbose_name='Nombre')
    phone =  models.DecimalField(max_digits=10, decimal_places=0, verbose_name='Telefono', unique=True)
    email = models.EmailField(blank=True)
    def __str__(self):
        return self.name + " - " + str(self.phone)[-3::]
    class Meta:
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

class Order(models.Model):
    CONFIRM_CHOICES = ((False, 'Borrador'), (True, 'Confirmado'),)
    order = models.CharField(max_length=140, verbose_name='descripción / notas', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    client = models.ForeignKey(Client, null=True, on_delete=models.SET_NULL, verbose_name='cliente')
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField('Item', through='Qty')
    comments = models.TextField(max_length=140, blank=True, verbose_name='comentarios')
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    paid = models.DecimalField(max_digits=9, decimal_places=2,
                               default=0, verbose_name='abono')
    #paid = models.DecimalField(max_digits=9, decimal_places=2,
     #                          default=0, verbose_name='abono', validators=[MinValueValidator(0.00)])

    discount = models.DecimalField(max_digits=9, decimal_places=2,
                               default=0, verbose_name='descuento')
    debt = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='saldo')
    due_date = models.DateField(default= datetime.now()+timedelta(days=15),
                                verbose_name= 'Fecha de entrega', help_text="ejemplo: 2019-05-28")
    confirmed = models.BooleanField(choices=CONFIRM_CHOICES, default=False)
    completed = models.BooleanField(default=False)

    def add_items(self):
        return self.items.aggregate(total=models.Sum('price'))['total']

    def add_all_items(self):
        cnt = 0
        for qty in self.qty_set.all():
            cnt += qty.add_same_items()
            self.total = cnt
        return cnt

    def debts(self):
        self.debt = self.total - self.paid - self.discount

    def save(self, *args, **kwargs):
        if self.total == self.paid and self.paid != 0:
            self.completed = True
        super(Order, self).save(*args, **kwargs)





    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

class Institution(models.Model):
    name = models.CharField(max_length=50, verbose_name='nombre')
    name_slug = models.SlugField(unique=True, primary_key=True,
                                 max_length=50, verbose_name='codigo')
    def __str__(self):
        return self.name_slug

    class Meta:
        verbose_name = 'Institución/Categoria'
        verbose_name_plural = 'Instituciones/Categoria'

class Item(models.Model):
    name = models.CharField(max_length=90, verbose_name='nombre')
    size = models.CharField(max_length=25, verbose_name='talla')
    price = models.DecimalField(max_digits=9, decimal_places=2, default=0,
                                verbose_name='precio')
    #type = models.CharField(max_length=20)
    quantity = models.IntegerField(default=0, verbose_name='cantidad')
    created = models.DateTimeField(auto_now_add=True, verbose_name='creado')
    updated = models.DateTimeField(auto_now=True, verbose_name='actualizado')
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE,
                                    primary_key=False, verbose_name='institución')
    code = models.SlugField(max_length=90, verbose_name='codigo')
    prod_cost = models.DecimalField(max_digits=9, decimal_places=2, default=0,
                                verbose_name='precio producción')
    quantity_ordered = models.IntegerField(default=0, verbose_name='cantidad ordenada')
    quantity_needed = models.IntegerField(default=0, verbose_name='cantidad necesitada')

    def item_needed(self):
        sum = self.quantity_ordered - self.quantity
        if sum < 0:
            sum = 0
        self.quantity_needed = sum
        return sum

    def __str__(self):
        return self.code

    def save(self, *args, **kwargs):
        #if not self.code:
        self.code = slugify(self.name) + slugify(self.size) + slugify(self.institution)
        super(Item, self).save(*args, **kwargs)


    class Meta:
        verbose_name = 'producto'
        verbose_name_plural = 'productos'


class Qty(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    pending = models.IntegerField(default=1)

    def add_same_items(self):
        return self.quantity * self.item.price

    def get_dispatched_items(self):
        return  self.quantity - self.pending


class Payments(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    created = models.DateTimeField(auto_now_add=True)

mysite/mystore/views.py
import weasyprint
from django.conf import settings
from django.contrib.postgres.search import SearchVector, SearchQuery, \
    SearchRank, TrigramSimilarity
from django.core.mail import send_mail, EmailMultiAlternatives
from email.mime.image import MIMEImage
from django.core.paginator import Paginator, EmptyPage, \
    PageNotAnInteger
from django.db.models.functions import Greatest
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.generic import ListView
from .forms import OrderForm, SelForm, EmailPostForm, \
    SearchForm, ClientSearchForm, ClientForm, ItemSearchForm
from .models import Order, Item, Institution, Client, Payments


def IndexView(request):
    form = SearchForm()
    query = None
    if 'pedido' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['pedido']
            search_vector = SearchVector('id', 'client')
            search_query =SearchQuery(query)
            results = Order.objects.annotate(search=search_vector, rank=SearchRank(search_vector, search_query))\
                .filter(search=search_query).order_by('-rank')
    else:
        #results = Order.objects.filter(debt__gt=F('total')).order_by('created')
        results = Order.objects.all().order_by('-created')
    #context_object_name = 'orders'
    object_list = results
    paginator = Paginator(object_list, 10)  # 3 orders in each page
    page = request.GET.get('page')
    try:
        orders = paginator.page(page)
    except PageNotAnInteger:
    # If page is not an integer deliver the first page
        orders = paginator.page(1)
    except EmptyPage:
    # If page is out of range deliver last page of results
        orders = paginator.page(paginator.num_pages)

    return render(request, 'mystore/index.html', {'form': form,
                                                   'query': query,
                                                   'orders': orders
                                                   })

def detail(request, order_id, item_rmv=None, institution=None,
           size=None, item_dispatch=None, item_pending=None, item_missing=None):
    order = get_object_or_404(Order, pk=order_id)
    order.add_all_items()
    order_items_qty = order.qty_set.all().order_by('id')
    order.save()
    #check if any filter and assign the response
    response_page = HttpResponseRedirect(reverse('mystore:size', args=(order.id,
                                                                      institution,
                                                                      size)))
    #check if an item is to be removed
    if item_rmv != None:
        item_to_remove = order.qty_set.get(id=item_rmv)
        if item_to_remove.quantity == 1:
            order.qty_set.filter(id=item_rmv).delete()
            order.save()
            return response_page
        else:
            item_to_remove.quantity = item_to_remove.quantity - 1
            if item_to_remove.pending == 0:
                item_to_remove.save()
            else:
                item_to_remove.pending -= 1
                item_to_remove.save()
            return response_page

    if item_dispatch != None:
        item_dispatched = order.qty_set.get(id=item_dispatch)
        if item_pending !=0:
            item_dispatched.pending -= 1
            item_dispatched.save()
        return response_page

    if item_missing != None:
        item_dispatched = order.qty_set.get(id=item_missing)
        if item_pending < item_dispatched.quantity:
            item_dispatched.pending += 1
            item_dispatched.save()
        return response_page

    if request.method == 'POST':
        form = SelForm(request.POST)
        if form.is_valid():
            new_item = form.save(commit=False)
            item_form = new_item.item
            for qty in order_items_qty:
                if item_form == qty.item:
                    qty.quantity += 1
                    qty.pending +=1
                    qty.save()
                    order.save()
                    return response_page
            new_item.order = order
            new_item.save()
            return response_page
        else:
            try:
                institution = Institution.objects.get(pk=request.POST['inst'])
                size = request.POST['size']
            except (KeyError, Institution.DoesNotExist):
                form = SelForm()
                form.fields["item"].queryset = Item.objects.all()
            else:
                if size == None:
                    form.fields["item"].queryset = Item.objects.\
                        filter(institution=institution)
                    return HttpResponseRedirect(reverse('mystore:institution', args=(order.id,
                                                         institution)))
                else:
                    form = SelForm()
                    form.fields["item"].queryset = Item.objects. \
                        filter(institution=institution, size=size)
                    return HttpResponseRedirect(reverse('mystore:size', args=(order.id,
                                                                              institution,
                                                                              size)))
    else:
        if institution == None:
            form = SelForm()
        else:
            if size == None:
                form = SelForm()
                form.fields["item"].queryset = Item.objects. \
                                    filter(institution=institution)
            else:
                form = SelForm()
                form.fields["item"].queryset = Item.objects. \
                    filter(institution=institution, size=size)
    return render(request, 'mystore/detail.html', {'form': form,
                                                   'order': order,
                                                   'order_items_qty': order_items_qty,
                                                   'institution': institution, 'size': size},)

def add_order(request):

    if request.method == 'POST':
        # An order was added
        order_form = OrderForm(data=request.POST)
        if order_form.is_valid():
            new_order = Order(**order_form.cleaned_data)
            new_order.save()
            return HttpResponseRedirect(reverse('mystore:detail', args=(new_order.id,)))
    else:
        order_form = OrderForm()
    return render(request, 'mystore/add_order.html', {'order_form': order_form})

def confirmation(request, order_id):
    order = get_object_or_404(Order, pk=order_id)

    if order.confirmed == False:
        order_items = order.qty_set.all()
        for item in order_items:
            dispatched = item.quantity - item.pending
            if dispatched >= 0:
                item_stock = Item.objects.get(code=item.item)
                item_stock.quantity -= dispatched
                item_stock.quantity_ordered += item.pending
                item_stock.item_needed()
                item_stock.save()
        order.confirmed = True
        order.save()
        return HttpResponseRedirect(reverse('mystore:confirmation',
                                            args=(order.id,)))
    return render(request, 'mystore/confirmation.html', {'order': order})

def receipt(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    tax = float(order.total) * 0.19
    order.debts()
    order.save()
    return render(request, 'mystore/factura.html', {'order': order,
                                                    'tax': tax})

def order_update(request, order_id, item_dispatch=None,
                 item_missing=None, item_pending=0,):
    order = get_object_or_404(Order, pk=order_id)
    order_items_qty = order.qty_set.all().order_by('id')
    if item_dispatch != None:
        item_dispatched = order.qty_set.get(id=item_dispatch)
        if item_pending !=0:
            item_dispatched.pending -= 1
            item_dispatched.save()
            product = Item.objects.get(code=item_dispatched.item)
            product.quantity -= 1
            product.quantity_ordered -= 1
            product.item_needed()
            product.save()
        return HttpResponseRedirect(reverse('mystore:order_update', args=(order.id,)))

    if item_missing != None:
        item_dispatched = order.qty_set.get(id=item_missing)
        if item_pending < item_dispatched.quantity:
            item_dispatched.pending += 1
            item_dispatched.save()
            product = Item.objects.get(code=item_dispatched.item)
            product.quantity += 1
            product.quantity_ordered += 1
            product.item_needed()
            product.save()
        return HttpResponseRedirect(reverse('mystore:order_update', args=(order.id,)))

    return render(request, 'mystore/order_update.html', {'order': order,
                                                         'order_items_qty': order_items_qty,
                                                         })

def order_share(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    html_email = render_to_string("mystore/factura_email.html",{'order':order})
    subject_email = "Tu recibo de compra, Margitex"
    from_email = "margitex@margitex.com"
    to_email = order.client.email
    msg = EmailMultiAlternatives(subject_email,html_email, from_email, [to_email])
    msg.attach_alternative(html_email, "mystore/factura.html")
    msg.content_subtype = 'html'
    msg.mixed_subtype = 'related'

    img = open("static/mystore/martha1.png",'rb').read()
    image =MIMEImage(img, 'png')
    image.add_header('Content-ID','<{}>'.format('/static/mystore/martha1.png'))
    image.add_header('Content-Disposition', 'inline', filename='/static/mystore/martha1.png')
    msg.attach(image)

mysite/mystore/templates/mystore/add_client.html
{% extends "mystore/base.html" %}
{% block title %}Client nuevo{% endblock %}
{% block content %}
<h1>Agregar Cliente</h1>
    <form action="." method="post">
        {{ client_form.as_p }}
        {% csrf_token %}
        <p><input  type="submit" class="btn btn-primary" value="Agregar Cliente"></p>
    </form>
{% endblock %}

mysite/mystore/templates/mystore/base.html
{% load mystore_tags%}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'mystore/bootstrap.css' %}" rel="stylesheet">
        <script src="{% static 'mystore/js/bootstrap.js' %}" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="{% static 'mystore/js/bootstrap.min.js' %}" ></script>
        {% block styles %}

        {% endblock %}
    </head>
    <body>
        <ul class="nav justify-content-end">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'mystore:index' %}">Pedidos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'mystore:inventory' %}">Productos</a>
              </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mystore:add_item' %}">Agregar Producto </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mystore:item_search' %}">Buscar Producto </a>
              </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mystore:client_search' %}">Buscar Cliente </a>
              </li>

        </ul>
        <div id="container">
            {% block content %}

            {% endblock %}
        </div>

    </body>
</html>

mysite/mystore/templates/mystore/college_list.html
{%for cole in all_inst %}
    <option value="{{ cole.name_slug }}">{{cole.name}}</option>
{% endfor %}

mysite/mystore/templates/mystore/confirmation.html
{% extends "mystore/base.html" %}
{% load mystore_tags %}
{% block title %}Confirmar Pedido{% endblock %}
{% block content %}
<h1>Pagos y descuentos</h1>
<div class="row">
    <div class="col">
        <form action= "{% url 'mystore:order_payments' %}" method="POST">
            {% csrf_token %}
            <label for="amount">Abono</label>
            <input type="number" name="amount" id="amount">
            <input type="hidden" name="next" value="{{ request.path }}">
            <input type="hidden" name="order_id" value="{{ order.id }}">
            <p><input type="submit" value="aplicar"></p>
        </form>
    </div>
    <div class="col">
        <table class="table table-striped table-sm">
            <tr>
                <th scope="col">Abono</th>
                <th scope="col">Fecha</th>
                <th scope="col">vendedor</th>
            </tr>
            {% for pay in order.payments_set.all %}
                <tr>
                    <td {% if pay.payment < 0 %} class="alert alert-danger"{% endif %} > {{ pay.payment }}</td>
                    <td>{{ pay.created }}</td>
                    <td>{{ order.added_by }}</td>
                </tr>

            {% endfor %}
        </table>
    </div>
</div>
<table class="table">
    <thead>
        <tr class="d-flex">
            <th class="col-2">Costo Total</th>
            <th class="col-2">Pagado</th>
            <th class="col-2">Descuento</th>
            <th class="col-4">Total a Pagar</th>
        </tr>
    </thead>
    <tbody>
        <tr class="d-flex">
            <td class="col-2" >${{order.total}}</td>
            <td class="col-2">${{order.paid}}</td>
            <td class="col-2">${{order.discount}}</td>
            <td class="col-4 table-success"><em>${{order.debt}}</em></td>
        </tr>
    </tbody>
</table>

    <a href="{% url 'mystore:order_share' order.id %}" class="btn btn-primary">enviar email</a>
    <a href="{% url 'mystore:receipt' order.id %}" class="btn btn-primary">ver factura</a>

{% endblock %}

mysite/mystore/templates/mystore/filter.html
<form action="{% url 'mystore:institution' order.id %}" method="post">
    {% csrf_token %}
    <label for="inst">Colegio</label>
    <select id="inst" name="inst">
        {%for cole in college%}
            <option value="{{ cole }}">{{cole.name}}</option>
        {% endfor %}
    </select>
    <input type="submit" value="seleccionar">
</form>

mysite/mystore/templates/mystore/index.html
{% extends "mystore/base.html" %}
{% load static %}

{% block title %}Margitex{% endblock %}
{% block content %}
    {% if orders %}
        <form class="form-inline"  action="." method="get">
            <div class="form-group mb-2">
                {{ form.as_table }}
                <input type="submit" class="btn btn-outline-primary " value="Buscar" >
                <a href=" {% url 'mystore:index' %}" class="btn btn-outline-primary"> mostrar todos</a>
            </div>
        </form>

        <a class="btn btn-primary btn-lg btn-block font-weight-bold" href="{% url 'mystore:add_order' %}">Agregar Pedido</a>
    <h2>Lista de pedidos</h2>
<ul>
    <div class="row">
        {% for order in orders %}
         <div class="col-md-6">
            <div class="card">
                <h5 class="card-header">Pedido: {{ order.id }}</h5>
                <div class="card-body">
                    <li><p>{{ order.client}} - Entrega: {{ order.due_date|date:"d - m - Y"}} </p></li>
                <span class="badge badge-info">{{order.order}}</span>
                    {% if order.completed%}
                <span class="badge badge-success">PAGADA</span>
                    {% endif %}
                <a .card-link href="{% url 'mystore:order_update' order.id %}" class="btn btn-outline-primary btn-sm"> actualizar</a>
                {% if order.confirmed == False%}
                    <a .card-link href="{% url 'mystore:detail' order.id %}" class="btn btn-primary btn-sm"> finalizar Pedido</a>
                {% endif %}
                </div>
            </div>
         </div>
        {% endfor %}
        </div>
        </ul>
    {% else %}
        <p>Ningun pedido ha sido agregado</p>
<a class="btn btn-primary btn-lg btn-block" href="{% url 'mystore:add_order' %}"> agregar pedido</a>
    {% endif %}
        <div id="pagination">
            {% include "pagination.html" with page=orders %}
        </div>
{% endblock %}

mysite/mystore/templates/mystore/inventory.html
{% extends "mystore/base.html" %}
{% load static %}

{% block title %}Productos{% endblock %}
{% block content %}
    {% if products %}

<h2>Lista de productos</h2>
<ul>
    <div class="row">

    {% for item in products %}
 <div class="col-md-6">
            <div class="card">
                <h5 class="card-header">{{ item.name|title }}  {{ item.size}} - {{ item.institution.name }}</h5>
                <div class="card-title">
                    <ul class="list-group">
                        <li class="list-group-item">Cantidad en inventario: {{ item.quantity }}  -
                            Cantidad apartada: {{item.quantity_ordered }}</li>
                        <li class="list-group-item"><h3>Cantidad necesitada: {{ item.quantity_needed }}</h3></li>
                    </ul>
                    <span class="badge badge-pill badge-primary">{{ item.code }}</span>
                </div>
            </div>
     </div>
    {% endfor %}
        </div>
</ul>
    {% else %}
        <p>Ningun producto ha sido agregado</p>
     {% endif %}
        <div id="pagination">
            {% include "pagination.html" with page=page_obj %}
        </div>
{% endblock %}

mysite/mystore/templates/mystore/item_search.html
{% extends "mystore/base.html" %}
{% block title %}Buscar Producto{% endblock %}
{% block content %}

{% if products %}
<h1>Productos que contienen "{{ query }}"</h1>
<h3>
    {% with products.count as total_results %}
    Encontrado: {{ total_results }} resultado{{ total_results|pluralize }}
    {% endwith %}
</h3>
<p><a href="{% url 'mystore:item_search' %}">Buscar otra vez</a></p>
{% for item in products %}
    <div class="card">
                <h5 class="card-header">{{ item.name|title }}  {{ item.size}} - {{ item.institution.name }}
                </h5>
                <div class="card-title">
                    <ul class="list-group">
                        <li class="list-group-item">Cantidad en inventario: {{ item.quantity }}  -
                            Cantidad apartada: {{item.quantity_ordered }}</li>
                        <li class="list-group-item"><h3>Cantidad necesitada: {{ item.quantity_needed }}</h3></li>
                    </ul>
                    <span class="badge badge-pill badge-primary">{{ item.code }}</span>
                </div>
    </div>
{% empty %}
<p>Tu busqueda no produjo ningun resultado</p>
{% endfor %}
{% else %}
<h1>Buscar Productos</h1>
<form class="form-inline"  action="." method="get">
    <div class="form-group mb-2">
        {{ form.as_table }}
        <input type="submit" class="btn btn-outline-primary " value="Buscar" >
    </div>
</form>
{% endif %}
{% endblock %}

mysite/mystore/templates/mystore/order_receipt.html
{% load static %}
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'mystore/style.css' %}" rel="stylesheet">
    </head>
<body>
<div id="invoice-POS">

    <center id="top">
      <div class="logo"></div>
      <div class="info">
        <h1>MARGITEX</h1>
		   <h2>Martha Romero</h2>
      </div><!--End Info-->
    </center><!--End InvoiceTop-->

    <div id="mid">
      <div class="info">

        <p>
            Dirección : Transversal 12</br>
            Email   : JohnDoe@gmail.com</br>
            telefono   : 555-555-5555</br>
        </p>
      </div>
    </div><!--End Invoice Mid-->

    <div class="bot">
						<table>
							<tr>
								<td width="200" height="20"><p style="font-size:14px;">Producto </p></td>
								<td width="50" height="20"><p style="font-size:14px;">Cantidad</p></td>
								<td width="100" height="20"><p style="font-size:14px;">SubTotal</p></td>
							</tr>
							{%for item_order in order.qty_set.all%}
							<tr>
								<td width="200" height="20"><p style="font-size:10px;">{{item_order.item.code}}</p></td>
								<td width="50" height="20"><p style="font-size:12px;text-align:center">{{item_order.quantity }}</p></td>
								<td width="100" height="20"><p style="font-size:12px;">${{item_order.add_same_items}}</p></td>
							</tr>
							{% endfor %}
							<tr>
								<td width="50" height="10"></td>
								<td width="50" height="10"><h3>IVA</h3></td>
								<td width="50" height="10"><h3>${{ tax }}</h3></td>
							</tr>
							<tr>
								<td width="50" height="10"></td>
								<td width="50" height="10"><h3>Total</h3></td>
								<td width="50" height="10"><h3>${{ order.add_all_items}}</h3></td>
							</tr>
							<tr>
								<td width="50" height="10"></td>
								<td width="50" height="10"><h3>Abono</h3></td>
								<td width="50" height="10"><h3>${{ order.paid}}</h3></td>
							</tr>
							<tr>
								<td width="50" height="10"></td>
								<td width="50" height="10"><h2>A pagar</h2></td>
								<td width="50" height="10"><h2>${{ order.debt}}</h2></td>
							</tr>

						</table>
	</div>

					<div id="legalcopy">
						<p class="legal"><strong>Gracias por su compra</strong> 	Por favor conserve este recibo.</p>
					</div>


  </div><!--End Invoice-->

</body>
</html>

mysite/mystore/templates/mystore/search.html
{% extends "mystore/base.html" %}
{% block title %}Buscar Pedido{% endblock %}
{% block content %}
{% if query %}
<h1>Pedidos que contienen "{{ query }}"</h1>
<h3>
    {% with results.count as total_results %}
    Encontrado: {{ total_results }} resultado{{ total_results|pluralize }}
    {% endwith %}
</h3>
{% for order in results %}
<h4><a href="{% url 'mystore:order_update' order.id %}">Pedido: {{ order.id }}</a></h4>
{% empty %}
<p>Tu busqueda no produjo ningun resultado</p>
{% endfor %}
<p><a href="{% url 'mystore:order_search' %}">Buscar otra vez</a></p>
{% else %}
<h1>Buscar Pedido</h1>
<p>Digite el numero del pedido:</p>
<form action="." method="get">
{{ form.as_p }}
<input type="submit" value="Buscar">
</form>
{% endif %}
{% endblock %}

mysite/mystore/templates/mystore/share.html
{% extends "mystore/base.html" %}
{% load static %}

{% block title %}Share a post{% endblock %}
{% block content %}
{% if sent %}
    <h1>E-mail enviado exitosamente!</h1>
    <p>La confirmacion del pedido fue enviada a {{ form.cleaned_data.to}}.</p>
    <a href="{% url 'mystore:receipt' order.id %}" class="btn btn-primary">ver factura</a>
{% else %}
    <h1>La factura no fue enviada confirmacion del pedido: "{{ order.id }}"</h1>
{% endif %}
{% endblock %}l>

mysite/mystore/templates/mystore/size_list.html
{%for size in sizes %}
    <option value="{{ size }}">{{size}}</option>
{% endfor %}